server:
  port: 8500
spring:
  application:
    name: opportunities-handler
  datasource:
    url: jdbc:postgresql://localhost:5432/mobiauto
    username: user
    password: password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    schemas: opportunities-handler
    baselineOnMigrate: true
    locations: classpath:db/migration
jwt:
  secret: ${JWT_SECRET:"MySecretKeyMySecretKeyMySecretKeyMySecret!}