server:
  port: 8100
spring:
  application:
    name: auth-manager
  datasource:
    url: jdbc:postgresql://localhost:5432/mobiauto
    username: user
    password: password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    baselineOnMigrate: true
    locations: classpath:db/migration
    schemas: auth

jwt:
  secret: ${JWT_SECRET:"MySecretKeyMySecretKeyMySecretKeyMySecret!}